name: macOS DMG (unsigned)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter --version
      - run: flutter config --enable-macos-desktop
      - run: flutter pub get

      - name: Build macOS (Release)
        run: flutter build macos --release

      - name: Install create-dmg
        run: brew install create-dmg

      - name: Create DMG
        run: |
          APP=$(ls -d build/macos/Build/Products/Release/*.app | head -n 1)
          if [ -z "$APP" ]; then
            echo "No .app found in Release output"; exit 1
          fi
          NAME=$(basename "$APP" .app)
          mkdir -p dist
          create-dmg --no-internet-enable --volname "$NAME" "dist/$NAME.dmg" "$APP"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-dmg-unsigned
          path: dist/*.dmg
